#!/usr/bin/env bash

# Based on https://github.com/commercialhaskell/hindent/issues/309#issue-180517159

set -e

HINDENT=hindent
GIT=git

LINE_LENGTH=80

function hindent_file {
    filename="$1"
    output_filename="${filename}.hindented"
    # In hindent 0.5+, the style is hard-coded to johan-tibell
    ${HINDENT} --style johan-tibell --line-length "${LINE_LENGTH}" < "${filename}" > "${output_filename}"
    mv "${output_filename}" "${filename}"
}

function list_haskell_files {
    # TODO: Figure out if it's a Haskell file in a more reliable way, e.g.
    # using `file`, or just running hindent on everything.

    # TODO: Exclude ./src/Settings.hs, due to https://github.com/commercialhaskell/hindent/issues/383
    ${GIT} ls-files './*.hs'
}

function indent_everything {
    for filename in $(list_haskell_files); do
        hindent_file "${filename}"
    done
}

indent_everything
